<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="THINK-M4480-11" name="Registration" tests="17" failures="13" timestamp="9 Apr 2015 15:11:49 GMT" time="219.375" errors="0">
  <testcase name="SuccessToRegisterUsersForAllProvinces" time="15.992" classname="test_cases.RegistrationTest">
    <failure type="java.lang.Throwable" message="Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [http://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
nnFailure 2 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [http://stg-club.websaver.ca/app_stage.php/en_ca/registration/]">
      <![CDATA[java.lang.Throwable: Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [http://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
nnFailure 2 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [http://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
... Removed 56 stack frames]]>
    </failure>
  </testcase> <!-- SuccessToRegisterUsersForAllProvinces -->
  <testcase name="SuccessToRegisterUsersForAllProvinces" time="8.781" classname="test_cases.RegistrationTest">
    <failure type="java.lang.Throwable" message="Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
nnFailure 2 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]">
      <![CDATA[java.lang.Throwable: Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
nnFailure 2 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
... Removed 56 stack frames]]>
    </failure>
  </testcase> <!-- SuccessToRegisterUsersForAllProvinces -->
  <testcase name="SuccessToRegisterUsersForAllProvinces" time="7.055" classname="test_cases.RegistrationTest">
    <failure type="java.lang.Throwable" message="Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
nnFailure 2 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]">
      <![CDATA[java.lang.Throwable: Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
nnFailure 2 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
... Removed 56 stack frames]]>
    </failure>
  </testcase> <!-- SuccessToRegisterUsersForAllProvinces -->
  <testcase name="SuccessToRegisterUsersForAllProvinces" time="5.894" classname="test_cases.RegistrationTest">
    <failure type="org.openqa.selenium.ElementNotVisibleException" message="Element is not currently visible and so may not be interacted with
Command duration or timeout: 3.11 seconds
Build info: version: &amp;apos;2.45.0&amp;apos;, revision: &amp;apos;32a636c&amp;apos;, time: &amp;apos;2015-03-05 22:01:35&amp;apos;
System info: host: &amp;apos;THINK-M4480-11&amp;apos;, ip: &amp;apos;192.168.1.151&amp;apos;, os.name: &amp;apos;Windows 7&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;6.1&amp;apos;, java.version: &amp;apos;1.8.0_40&amp;apos;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=37.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 9b497739-a6db-490f-9e1c-d43d661b654d">
      <![CDATA[org.openqa.selenium.ElementNotVisibleException: Element is not currently visible and so may not be interacted with
Command duration or timeout: 3.11 seconds
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'THINK-M4480-11', ip: '192.168.1.151', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_40'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=37.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 9b497739-a6db-490f-9e1c-d43d661b654d
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:89)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:50)
	at com.sun.proxy.$Proxy9.sendKeys(Unknown Source)
	at websaver_pages.RegistrationPage.registerUser(RegistrationPage.java:148)
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:49)
Caused by: org.openqa.selenium.ElementNotVisibleException: Element is not currently visible and so may not be interacted with
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'THINK-M4480-11', ip: '192.168.1.151', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_40'
Driver info: driver.version: unknown
	at <anonymous class>.fxdriver.preconditions.visible(file:///C:/Users/RICARD~1.OQU/AppData/Local/Temp/anonymous4879745980551035641webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:9587)
	at <anonymous class>.DelayedCommand.prototype.checkPreconditions_(file:///C:/Users/RICARD~1.OQU/AppData/Local/Temp/anonymous4879745980551035641webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12257)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///C:/Users/RICARD~1.OQU/AppData/Local/Temp/anonymous4879745980551035641webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12274)
	at <anonymous class>.fxdriver.Timer.prototype.setTimeout/<.notify(file:///C:/Users/RICARD~1.OQU/AppData/Local/Temp/anonymous4879745980551035641webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:603)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- SuccessToRegisterUsersForAllProvinces -->
  <testcase name="SuccessToRegisterUsersForAllProvinces" time="5.85" classname="test_cases.RegistrationTest">
    <failure type="org.openqa.selenium.ElementNotVisibleException" message="Element is not currently visible and so may not be interacted with
Command duration or timeout: 3.13 seconds
Build info: version: &amp;apos;2.45.0&amp;apos;, revision: &amp;apos;32a636c&amp;apos;, time: &amp;apos;2015-03-05 22:01:35&amp;apos;
System info: host: &amp;apos;THINK-M4480-11&amp;apos;, ip: &amp;apos;192.168.1.151&amp;apos;, os.name: &amp;apos;Windows 7&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;6.1&amp;apos;, java.version: &amp;apos;1.8.0_40&amp;apos;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=37.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: ae269788-1663-4a27-867c-63c9f6bcc878">
      <![CDATA[org.openqa.selenium.ElementNotVisibleException: Element is not currently visible and so may not be interacted with
Command duration or timeout: 3.13 seconds
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'THINK-M4480-11', ip: '192.168.1.151', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_40'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=37.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: ae269788-1663-4a27-867c-63c9f6bcc878
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:89)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:50)
	at com.sun.proxy.$Proxy9.sendKeys(Unknown Source)
	at websaver_pages.RegistrationPage.registerUser(RegistrationPage.java:148)
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:49)
Caused by: org.openqa.selenium.ElementNotVisibleException: Element is not currently visible and so may not be interacted with
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'THINK-M4480-11', ip: '192.168.1.151', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_40'
Driver info: driver.version: unknown
	at <anonymous class>.fxdriver.preconditions.visible(file:///C:/Users/RICARD~1.OQU/AppData/Local/Temp/anonymous1203800560541778383webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:9587)
	at <anonymous class>.DelayedCommand.prototype.checkPreconditions_(file:///C:/Users/RICARD~1.OQU/AppData/Local/Temp/anonymous1203800560541778383webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12257)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///C:/Users/RICARD~1.OQU/AppData/Local/Temp/anonymous1203800560541778383webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12274)
	at <anonymous class>.fxdriver.Timer.prototype.setTimeout/<.notify(file:///C:/Users/RICARD~1.OQU/AppData/Local/Temp/anonymous1203800560541778383webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:603)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- SuccessToRegisterUsersForAllProvinces -->
  <testcase name="SuccessToRegisterUsersForAllProvinces" time="5.893" classname="test_cases.RegistrationTest">
    <failure type="java.lang.Throwable" message="Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
nnFailure 2 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]">
      <![CDATA[java.lang.Throwable: Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
nnFailure 2 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
... Removed 56 stack frames]]>
    </failure>
  </testcase> <!-- SuccessToRegisterUsersForAllProvinces -->
  <testcase name="SuccessToRegisterUsersForAllProvinces" time="5.439" classname="test_cases.RegistrationTest">
    <failure type="java.lang.Throwable" message="Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
nnFailure 2 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]">
      <![CDATA[java.lang.Throwable: Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
nnFailure 2 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
... Removed 56 stack frames]]>
    </failure>
  </testcase> <!-- SuccessToRegisterUsersForAllProvinces -->
  <testcase name="SuccessToRegisterUsersForAllProvinces" time="5.952" classname="test_cases.RegistrationTest">
    <failure type="java.lang.Throwable" message="Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [http://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
nnFailure 2 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [http://stg-club.websaver.ca/app_stage.php/en_ca/registration/]">
      <![CDATA[java.lang.Throwable: Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [http://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
nnFailure 2 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [http://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
... Removed 56 stack frames]]>
    </failure>
  </testcase> <!-- SuccessToRegisterUsersForAllProvinces -->
  <testcase name="SuccessToRegisterUsersForAllProvinces" time="5.495" classname="test_cases.RegistrationTest">
    <failure type="java.lang.Throwable" message="Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
nnFailure 2 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]">
      <![CDATA[java.lang.Throwable: Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
nnFailure 2 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
... Removed 56 stack frames]]>
    </failure>
  </testcase> <!-- SuccessToRegisterUsersForAllProvinces -->
  <testcase name="SuccessToRegisterUsersForAllProvinces" time="5.669" classname="test_cases.RegistrationTest">
    <failure type="java.lang.Throwable" message="Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [http://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
nnFailure 2 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [http://stg-club.websaver.ca/app_stage.php/en_ca/registration/]">
      <![CDATA[java.lang.Throwable: Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [http://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
nnFailure 2 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [http://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
... Removed 56 stack frames]]>
    </failure>
  </testcase> <!-- SuccessToRegisterUsersForAllProvinces -->
  <testcase name="SuccessToRegisterUsersForAllProvinces" time="5.848" classname="test_cases.RegistrationTest">
    <failure type="org.openqa.selenium.ElementNotVisibleException" message="Element is not currently visible and so may not be interacted with
Command duration or timeout: 3.11 seconds
Build info: version: &amp;apos;2.45.0&amp;apos;, revision: &amp;apos;32a636c&amp;apos;, time: &amp;apos;2015-03-05 22:01:35&amp;apos;
System info: host: &amp;apos;THINK-M4480-11&amp;apos;, ip: &amp;apos;192.168.1.151&amp;apos;, os.name: &amp;apos;Windows 7&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;6.1&amp;apos;, java.version: &amp;apos;1.8.0_40&amp;apos;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=37.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: d97f91f4-0321-4e52-9d8c-87059ae37454">
      <![CDATA[org.openqa.selenium.ElementNotVisibleException: Element is not currently visible and so may not be interacted with
Command duration or timeout: 3.11 seconds
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'THINK-M4480-11', ip: '192.168.1.151', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_40'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=37.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: d97f91f4-0321-4e52-9d8c-87059ae37454
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:89)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:50)
	at com.sun.proxy.$Proxy9.sendKeys(Unknown Source)
	at websaver_pages.RegistrationPage.registerUser(RegistrationPage.java:148)
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:49)
Caused by: org.openqa.selenium.ElementNotVisibleException: Element is not currently visible and so may not be interacted with
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'THINK-M4480-11', ip: '192.168.1.151', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_40'
Driver info: driver.version: unknown
	at <anonymous class>.fxdriver.preconditions.visible(file:///C:/Users/RICARD~1.OQU/AppData/Local/Temp/anonymous3595200480812524691webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:9587)
	at <anonymous class>.DelayedCommand.prototype.checkPreconditions_(file:///C:/Users/RICARD~1.OQU/AppData/Local/Temp/anonymous3595200480812524691webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12257)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///C:/Users/RICARD~1.OQU/AppData/Local/Temp/anonymous3595200480812524691webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12274)
	at <anonymous class>.fxdriver.Timer.prototype.setTimeout/<.notify(file:///C:/Users/RICARD~1.OQU/AppData/Local/Temp/anonymous3595200480812524691webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:603)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- SuccessToRegisterUsersForAllProvinces -->
  <testcase name="SuccessToRegisterUsersForAllProvinces" time="8.979" classname="test_cases.RegistrationTest">
    <failure type="java.lang.Throwable" message="Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
nnFailure 2 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]">
      <![CDATA[java.lang.Throwable: Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
nnFailure 2 of 2:njava.lang.AssertionError: expected [http://stg-club.websaver.ca/app_stage.php/en/survey/] but found [https://stg-club.websaver.ca/app_stage.php/en_ca/registration/]
	at test_cases.RegistrationTest.SuccessToRegisterUsersForAllProvinces(RegistrationTest.java:55)
... Removed 56 stack frames]]>
    </failure>
  </testcase> <!-- SuccessToRegisterUsersForAllProvinces -->
  <testcase name="submitRegistrationWithAddressNotFound" time="0.001" classname="test_cases.RegistrationTest"/>
  <testcase name="submitRegistrationWithDifferentAddress" time="0.0" classname="test_cases.RegistrationTest"/>
  <testcase name="FailToSubmitRegistrationIfMandatoryFieldsAreMissing" time="3.081" classname="test_cases.RegistrationTest">
    <failure type="java.lang.Throwable" message="Multiple failures (3):nnFailure 1 of 3:njava.lang.AssertionError: expected [Please enter your First Name.] but found [Please enter your First Name.LAUNCH ERROR]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at test_cases.RegistrationTest.FailToSubmitRegistrationIfMandatoryFieldsAreMissing(RegistrationTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
nnFailure 2 of 3:njava.lang.AssertionError: expected [Please enter an e-mail address.] but found [Please enter an e-mail address.LAUNCH ERROR]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at test_cases.RegistrationTest.FailToSubmitRegistrationIfMandatoryFieldsAreMissing(RegistrationTest.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
nnFailure 3 of 3:njava.lang.Throwable: Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [Please enter your First Name.] but found [Please enter your First Name.LAUNCH ERROR]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at test_cases.RegistrationTest.FailToSubmitRegistrationIfMandatoryFieldsAreMissing(RegistrationTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
nnFailure 2 of 2:njava.lang.AssertionError: expected [Please enter an e-mail address.] but found [Please enter an e-mail address.LAUNCH ERROR]">
      <![CDATA[java.lang.Throwable: Multiple failures (3):nnFailure 1 of 3:njava.lang.AssertionError: expected [Please enter your First Name.] but found [Please enter your First Name.LAUNCH ERROR]
	at test_cases.RegistrationTest.FailToSubmitRegistrationIfMandatoryFieldsAreMissing(RegistrationTest.java:74)
nnFailure 2 of 3:njava.lang.AssertionError: expected [Please enter an e-mail address.] but found [Please enter an e-mail address.LAUNCH ERROR]
	at test_cases.RegistrationTest.FailToSubmitRegistrationIfMandatoryFieldsAreMissing(RegistrationTest.java:88)
nnFailure 3 of 3:njava.lang.Throwable: Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [Please enter your First Name.] but found [Please enter your First Name.LAUNCH ERROR]
	at test_cases.RegistrationTest.FailToSubmitRegistrationIfMandatoryFieldsAreMissing(RegistrationTest.java:74)
nnFailure 2 of 2:njava.lang.AssertionError: expected [Please enter an e-mail address.] but found [Please enter an e-mail address.LAUNCH ERROR]
	at test_cases.RegistrationTest.FailToSubmitRegistrationIfMandatoryFieldsAreMissing(RegistrationTest.java:88)
... Removed 112 stack frames]]>
    </failure>
  </testcase> <!-- FailToSubmitRegistrationIfMandatoryFieldsAreMissing -->
  <testcase name="UserNotSubmittedIfFeldsAreInvalid" time="0.0" classname="test_cases.RegistrationTest"/>
  <testcase name="UserNotSubmittedIfPasswordAndConfirmationPassowrdAreDifferent" time="0.0" classname="test_cases.RegistrationTest"/>
</testsuite> <!-- Registration -->
